# Generated by Django 5.1.2 on 2024-10-31 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(blank=True, max_length=6, null=True)),
                ('trade_signal', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea_candle', models.ImageField(blank=True, null=True, upload_to='idea_candles/')),
                ('line_graph_candle', models.ImageField(blank=True, null=True, upload_to='line_graph_candles/')),
                ('signal_candle', models.ImageField(blank=True, null=True, upload_to='signal_candles/')),
                ('hour_candle', models.ImageField(blank=True, null=True, upload_to='hour_candles/')),
                ('entry_candle', models.ImageField(blank=True, null=True, upload_to='entry_candle/')),
                ('take_profit_one_candle', models.ImageField(blank=True, null=True, upload_to='take_profit_one_candle/')),
                ('take_profit_two_candle', models.ImageField(blank=True, null=True, upload_to='take_profit_two_candle/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trade detail',
                'verbose_name_plural': 'Trade details',
            },
        ),
    ]
