# Generated by Django 5.1.2 on 2024-10-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradedetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedetails',
            name='trade_signal',
            field=models.CharField(blank=True, choices=[('BUYS', 'Buy'), ('SELLS', 'Sell')], max_length=5, null=True),
        ),
    ]
