# Generated by Django 5.1.2 on 2024-10-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradedetails', '0002_alter_tradedetails_trade_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedetails',
            name='trade_signal',
            field=models.CharField(blank=True, choices=[('BUYS', 'BUYS'), ('SELLS', 'SELLS')], max_length=5, null=True),
        ),
    ]
