# Generated by Django 5.1.2 on 2024-11-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradedetails', '0003_alter_tradedetails_trade_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedetails',
            name='breakeven_candle',
            field=models.ImageField(blank=True, null=True, upload_to='breakeven_candle/'),
        ),
        migrations.AddField(
            model_name='tradedetails',
            name='two_hour_candle',
            field=models.ImageField(blank=True, null=True, upload_to='two_hour_candles/'),
        ),
    ]
