# Generated by Django 5.1.2 on 2024-10-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='region',
        ),
    ]
